# Generated by Django 5.1.3 on 2024-11-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentTable',
        ),
    ]
